routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Admin\AdminHomeController@index')->name('admin.home');

Route::resource('/settings', 'Admin\AdminSettingController', ['as' => 'admin'])->except(['index', 'show']);
Route::resource('/products', 'Admin\AdminProductController', ['as' => 'admin'])->except(['show']);

Route::resource('/contents/faq', 'Admin\AdminFaqController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/faq', 'Admin\AdminFaqController@updateOrdering')->name('admin.contents.faq.ordering');

Route::resource('/contents/term', 'Admin\AdminTermController', ['as' => 'admin.contents'])->only(['index']);

Route::resource('/contents/payment', 'Admin\AdminPaymentController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/payment', 'Admin\AdminPaymentController@updateOrdering')->name('admin.contents.payment.ordering');

Route::resource('/contents/partner', 'Admin\AdminPartnerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/testimony', 'Admin\AdminTestimonyController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/promo', 'Admin\AdminPromoController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/banner', 'Admin\AdminBannerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/metas', 'Admin\AdminMetaController', ['as' => 'admin'])->except(['show']);

Route::resource('/users', 'Admin\AdminUserController', ['as' => 'admin'])->except(['show']);
Route::get('/users/profile', 'Admin\AdminUserController@showProfile')->name('admin.users.profile');
Route::put('/users/profile/update', 'Admin\AdminUserController@updateProfile')->name('admin.users.profile.update');
Route::put('/users/photo/update', 'Admin\AdminUserController@updatePhoto')->name('admin.users.photo.update');
Route::get('/users/password', 'Admin\AdminUserController@showPassword')->name('admin.users.password');
Route::put('/users/password/update', 'Admin\AdminUserController@updatePassword')->name('admin.users.password.update');

Route::resource('/simulations/installment', 'Admin\AdminInstallmentController', ['as' => 'admin.simulations'])->except(['index', 'show']);
Route::resource('/simulations', 'Admin\AdminSimulationController', ['as' => 'admin'])->except(['show']);
Route::get('/simulations/branch/update', 'Admin\AdminSimulationController@updateBranches')->name('admin.simulations.branch.update');

app/Models/Installment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Installment extends Model
{
    protected $guarded = [];
    protected $hidden = ['pivot'];
    protected $appends = array('label_duration');

    public function getLabelAttribute()
    {
        return $this->duration . ' bulan, ' . $this->rate . '%';
    }

    public function getLabelDurationAttribute()
    {
        return $this->duration . ' bulan';
    }

    public function getLabelRateAttribute()
    {
        return $this->rate . '%';
    }

    public function add($data)
    {
        return $this->create($data);
    }

    public function edit($data)
    {
        return $this->update($data);
    }
}

app/Models/Simulation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Simulation extends Model
{
    const MOBIL = '8';
    const MOTOR = '7';

    protected $guarded = [];

    public function updater()
    {
        return $this->belongsTo(User::class, 'updated_by')->withDefault(['name' => 'Tidak Diketahui']);
    }

    public function installments()
    {
        return $this->belongsToMany(Installment::class)->withTimestamps();
    }

    public function getCodeFormattedAttribute()
    {
        if ($this->attributes['code'] == Simulation::MOBIL)
        {
            return 'Mobil';
        }
        return 'Motor';
    }

    public function getUpdateAttribute()
    {
        $name = $this->updater->name;
        $datetime = new Carbon($this->updated_at);
        return $name . ', ' . $datetime->setTimezone('Asia/Jakarta')->format('d-m-Y, H:i');
    }

    public function add($data)
    {
        $dataWithUser = array_add(array_except($data, ['installments']), 'updated_by', auth()->user()->id);

        $meta = $this->create($dataWithUser);
        return $meta->installments()->sync(array_get($data, 'installments'));
    }

    public function edit($data)
    {
        $dataWithUser = array_add(array_except($data, ['installments']), 'updated_by', auth()->user()->id);

        $this->update($dataWithUser);
        return $this->installments()->sync(array_get($data, 'installments'));
    }
}

resources/views/admin/simulations/installment/create.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'simulation',
    ],
    'title' => 'Tambah Tenor',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Simulasi Kredit',
            'href' => route('admin.simulations.index'),
        ],
        [
            'title' => 'Tenor',
            'href' => route('admin.simulations.index'),
        ],
        [
            'title' => 'Tambah Tenor',
        ]
    ],
])

@section('title', 'Tambah Tenor')

@section('content')
    <div class="container-fluid ___simulation-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Tambah Tenor',
                'addons' => null,
            ])
                <form class="row" method="POST" action="{{ route('admin.simulations.installment.store') }}">
                    @csrf
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'duration',
                            'name' => 'duration',
                            'horizontal' => true,
                            'label' => 'LAMA TENOR',
                            'placeholder' => 'Masukkan lama tenor',
                            'type' => 'number',
                            'step' => '.01',
                            'value' => old('duration'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'rate',
                            'name' => 'rate',
                            'horizontal' => true,
                            'label' => 'PERSENTASE TENOR',
                            'placeholder' => 'Masukkan persentase tenor',
                            'type' => 'number',
                            'step' => '.01',
                            'value' => old('rate'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8 mr-t-10 d-flex justify-content-end flex-column flex-sm-row">
                        <a href="{{ route('admin.simulations.index') }}"><button class="btn btn-rounded btn-outline-default ripple mr-sm-3 mb-2 mb-sm-0" type="button">Batalkan</button></a>
                        <button class="btn btn-rounded btn-primary ripple" type="submit">Tambah Tenor</button>
                    </div>
                </form>
            @endcomponent
        </div>
    </div>
@endsection

resources/views/admin/simulations/installment/edit.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'simulation',
    ],
    'title' => 'Edit Tenor',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Simulasi Kredit',
            'href' => route('admin.simulations.index'),
        ],
        [
            'title' => 'Tenor',
            'href' => route('admin.simulations.index'),
        ],
        [
            'title' => 'Edit Tenor',
        ]
    ],
])

@section('title', 'Edit Tenor')

@section('content')
    <div class="container-fluid ___simulation-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Edit Tenor',
                'addons' => null,
            ])
                <form class="row" method="POST" action="{{ route('admin.simulations.installment.update', ['installment' => $installment['id']]) }}">
                    @csrf
                    @method('PUT')
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'duration',
                            'name' => 'duration',
                            'horizontal' => true,
                            'label' => 'LAMA TENOR',
                            'placeholder' => 'Masukkan lama tenor',
                            'type' => 'number',
                            'step' => '.01',
                            'value' => old('duration', $installment['duration']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'rate',
                            'name' => 'rate',
                            'horizontal' => true,
                            'label' => 'PERSENTASE TENOR',
                            'placeholder' => 'Masukkan persentase tenor',
                            'type' => 'number',
                            'step' => '.01',
                            'value' => old('rate', $installment['rate']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8 mr-t-10 d-flex justify-content-end flex-column flex-sm-row">
                        <a href="{{ route('admin.simulations.index') }}"><button class="btn btn-rounded btn-outline-default ripple mr-sm-3 mb-2 mb-sm-0" type="button">Batalkan</button></a>
                        <button class="btn btn-rounded btn-primary ripple" type="submit">Simpan Tenor</button>
                    </div>
                </form>
            @endcomponent
        </div>
    </div>
@endsection