routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Admin\AdminHomeController@index')->name('admin.home');

Route::resource('/settings', 'Admin\AdminSettingController', ['as' => 'admin'])->except(['index', 'show']);
Route::resource('/products', 'Admin\AdminProductController', ['as' => 'admin'])->except(['show']);

Route::resource('/contents/faq', 'Admin\AdminFaqController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/faq', 'Admin\AdminFaqController@updateOrdering')->name('admin.contents.faq.ordering');

Route::resource('/contents/term', 'Admin\AdminTermController', ['as' => 'admin.contents'])->only(['index']);

Route::resource('/contents/payment', 'Admin\AdminPaymentController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/payment', 'Admin\AdminPaymentController@updateOrdering')->name('admin.contents.payment.ordering');

Route::resource('/contents/partner', 'Admin\AdminPartnerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/testimony', 'Admin\AdminTestimonyController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/promo', 'Admin\AdminPromoController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/banner', 'Admin\AdminBannerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/metas', 'Admin\AdminMetaController', ['as' => 'admin'])->except(['show']);

Route::resource('/users', 'Admin\AdminUserController', ['as' => 'admin'])->except(['show']);
Route::get('/users/profile', 'Admin\AdminUserController@showProfile')->name('admin.users.profile');
Route::put('/users/profile/update', 'Admin\AdminUserController@updateProfile')->name('admin.users.profile.update');
Route::put('/users/photo/update', 'Admin\AdminUserController@updatePhoto')->name('admin.users.photo.update');
Route::get('/users/password', 'Admin\AdminUserController@showPassword')->name('admin.users.password');
Route::put('/users/password/update', 'Admin\AdminUserController@updatePassword')->name('admin.users.password.update');

Route::resource('/simulations/installment', 'Admin\AdminInstallmentController', ['as' => 'admin.simulations'])->except(['index', 'show']);
Route::resource('/simulations', 'Admin\AdminSimulationController', ['as' => 'admin'])->except(['show']);
Route::get('/simulations/branch/update', 'Admin\AdminSimulationController@updateBranches')->name('admin.simulations.branch.update');

resources/views/admin/contents/term/home.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'contents',
    ],
    'title' => 'Syarat dan Ketentuan',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Konten',
            'href' => 'javascript:void(0);',
        ],
        [
            'title' => 'Syarat dan Ketentuan',
        ]
    ],
])

@section('title', 'Syarat dan Ketentuan')

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" rel="stylesheet" type="text/css">
@endpush

@section('content')
    <div class="container-fluid ___contents-term-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Ubah Syarat dan Ketentuan',
                'addons' => null,
            ])
                <form id="___term-form" class="row" method="POST" action="{{ route('admin.settings.update', ['setting' => 'terms_conditions']) }}">
                    @csrf
                    @method('PUT')
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.editor', [
                            'id' => 'term-editor',
                            'name' => 'value',
                            'horizontal' => true,
                            'required' => true,
                            'label' => 'SYARAT DAN KETENTUAN',
                            'placeholder' => 'Masukkan syarat dan ketentuan',
                            'value' => old('value', $termsConditions),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8 mr-t-10 d-flex justify-content-end flex-column flex-sm-row">
                        <button class="btn btn-rounded btn-outline-default ripple mr-sm-3 mb-2 mb-sm-0" type="button" onclick="onResetForm();">Batalkan</button>
                        <button class="btn btn-rounded btn-primary ripple" type="submit">Simpan Perubahan</button>
                    </div>
                </form>
            @endcomponent
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>
@endpush

@push('scripts-app')
    <script src="{{ asset('js/admin/contents.term.js') }}"></script>
    <script>
        @if(session('status'))
            $.toast({
                heading: 'Permintaan Berhasil',
                text: "{{ session('status') }}",
                hideAfter : 7000,
                position: 'top-right',
                icon: 'success',
                stack: false
            });
        @endif
    </script>
@endpush