routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Admin\AdminHomeController@index')->name('admin.home');

Route::resource('/settings', 'Admin\AdminSettingController', ['as' => 'admin'])->except(['index', 'show']);
Route::resource('/products', 'Admin\AdminProductController', ['as' => 'admin'])->except(['show']);

Route::resource('/contents/faq', 'Admin\AdminFaqController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/faq', 'Admin\AdminFaqController@updateOrdering')->name('admin.contents.faq.ordering');

Route::resource('/contents/term', 'Admin\AdminTermController', ['as' => 'admin.contents'])->only(['index']);

Route::resource('/contents/payment', 'Admin\AdminPaymentController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/payment', 'Admin\AdminPaymentController@updateOrdering')->name('admin.contents.payment.ordering');

Route::resource('/contents/partner', 'Admin\AdminPartnerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/testimony', 'Admin\AdminTestimonyController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/promo', 'Admin\AdminPromoController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/banner', 'Admin\AdminBannerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/metas', 'Admin\AdminMetaController', ['as' => 'admin'])->except(['show']);

Route::resource('/users', 'Admin\AdminUserController', ['as' => 'admin'])->except(['show']);
Route::get('/users/profile', 'Admin\AdminUserController@showProfile')->name('admin.users.profile');
Route::put('/users/profile/update', 'Admin\AdminUserController@updateProfile')->name('admin.users.profile.update');
Route::put('/users/photo/update', 'Admin\AdminUserController@updatePhoto')->name('admin.users.photo.update');
Route::get('/users/password', 'Admin\AdminUserController@showPassword')->name('admin.users.password');
Route::put('/users/password/update', 'Admin\AdminUserController@updatePassword')->name('admin.users.password.update');

Route::resource('/simulations/installment', 'Admin\AdminInstallmentController', ['as' => 'admin.simulations'])->except(['index', 'show']);
Route::resource('/simulations', 'Admin\AdminSimulationController', ['as' => 'admin'])->except(['show']);
Route::get('/simulations/branch/update', 'Admin\AdminSimulationController@updateBranches')->name('admin.simulations.branch.update');

app/Models/Promo.php
<?php

namespace App\Models;

use App\Models\Image;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Promo extends Model
{
    protected $guarded = [];

    public function image()
    {
        return $this->hasOne(Image::class, 'id', 'image_id')->withDefault(['path' => config('setting.default.placeholder')]);
    }

    public function updater()
    {
        return $this->belongsTo(User::class, 'updated_by')->withDefault(['name' => 'Tidak Diketahui']);
    }

    public function getUpdateAttribute()
    {
        $name = $this->updater->name;
        $datetime = new Carbon($this->updated_at);
        return 'Pembaruan terakhir oleh ' . $name . ' pada ' . $datetime->setTimezone('Asia/Jakarta')->format('d-m-Y, H:i');
    }

    public function getSlugAttribute()
    {
        return str_slug($this->name, '-');
    }

    private function __populate($data, $image)
    {
        $dataWithoutLogo = array_except($data, ['image']);
        $dataWithImage = array_add($dataWithoutLogo, 'image_id', $image->id);
        $dataWithUser = array_add($dataWithImage, 'updated_by', auth()->user()->id);

        return $dataWithUser;
    }

    public function add($data)
    {
        $image = Image::add($data['image']);

        return $this->create($this->__populate($data, $image));
    }

    public function edit($data)
    {
        $image = $this->image;
        if (array_has($data, 'image'))
        {
            Image::remove($this->image);
            $image = Image::add($data['image']);
        }

        return $this->update($this->__populate($data, $image));

    }

    public function remove()
    {
        Image::remove($this->image);
        return $this->delete();
    }
}

resources/views/admin/contents/promo/create.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'contents',
    ],
    'title' => 'Tambah Promo',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Konten',
            'href' => 'javascript:void(0);',
        ],
        [
            'title' => 'Promo',
            'href' => route('admin.contents.promo.index'),
        ],
        [
            'title' => 'Tambah Promo',
        ]
    ],
])

@section('title', 'Tambah Promo')

@section('content')
    <div class="container-fluid ___product-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Tambah Promo',
                'addons' => null,
            ])
                <form class="row" method="POST" enctype="multipart/form-data" action="{{ route('admin.contents.promo.store') }}">
                    @csrf
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.uploader', [
                            'id' => 'image',
                            'name' => 'image',
                            'horizontal' => true,
                            'label' => 'GAMBAR PROMO',
                            'help' => 'Rekomendasi ukuran gambar 1600 x 900 px',
                            'value' => old('image'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'name',
                            'name' => 'name',
                            'horizontal' => true,
                            'label' => 'NAMA PROMO',
                            'placeholder' => 'Masukkan nama promo',
                            'value' => old('name'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.editor', [
                            'id' => 'description',
                            'name' => 'description',
                            'horizontal' => true,
                            'label' => 'DESKRIPSI PROMO',
                            'placeholder' => 'Masukkan deskripsi promo',
                            'value' => old('description'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8 mr-t-10 d-flex justify-content-end flex-column flex-sm-row">
                        <a href="{{ route('admin.contents.promo.index') }}"><button class="btn btn-rounded btn-outline-default ripple mr-sm-3 mb-2 mb-sm-0" type="button">Batalkan</button></a>
                        <button class="btn btn-rounded btn-primary ripple" type="submit">Tambah Promo</button>
                    </div>
                </form>
            @endcomponent
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
@endpush

@push('scripts-app')
    <script src="{{ asset('js/admin/contents.promo.create.js') }}"></script>
@endpush

resources/views/admin/contents/promo/edit.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'contents',
    ],
    'title' => 'Edit Promo',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Konten',
            'href' => 'javascript:void(0);',
        ],
        [
            'title' => 'Promo',
            'href' => route('admin.contents.promo.index'),
        ],
        [
            'title' => 'Edit Promo',
        ]
    ],
])

@section('title', 'Edit Promo')

@section('content')
    <div class="container-fluid ___product-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Edit Promo',
                'addons' => null,
            ])
                <form class="row" method="POST" enctype="multipart/form-data" action="{{ route('admin.contents.promo.update', ['promo' => $promo['id']]) }}">
                    @csrf
                    @method('PUT')
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.uploader', [
                            'id' => 'image',
                            'name' => 'image',
                            'horizontal' => true,
                            'label' => 'GAMBAR PROMO',
                            'help' => 'Biarkan kosong jika tidak ingin mengubah. Rekomendasi ukuran gambar 1600 x 900 px',
                            'value' => old('image', $promo['image']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'name',
                            'name' => 'name',
                            'horizontal' => true,
                            'label' => 'NAMA PROMO',
                            'placeholder' => 'Masukkan nama promo',
                            'value' => old('name', $promo['name']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.editor', [
                            'id' => 'description',
                            'name' => 'description',
                            'horizontal' => true,
                            'label' => 'DESKRIPSI PROMO',
                            'placeholder' => 'Masukkan deskripsi promo',
                            'value' => old('description', $promo['description']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8 mr-t-10 d-flex justify-content-end flex-column flex-sm-row">
                        <a href="{{ route('admin.contents.promo.index') }}"><button class="btn btn-rounded btn-outline-default ripple mr-sm-3 mb-2 mb-sm-0" type="button">Batalkan</button></a>
                        <button class="btn btn-rounded btn-primary ripple" type="submit">Simpan Promo</button>
                    </div>
                </form>
            @endcomponent
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/tinymce.min.js"></script>
@endpush

@push('scripts-app')
    <script src="{{ asset('js/admin/contents.promo.edit.js') }}"></script>
@endpush

resources/views/admin/contents/promo/home.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'contents',
    ],
    'title' => 'Promo',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Konten',
            'href' => 'javascript:void(0);',
        ],
        [
            'title' => 'Promo',
        ]
    ],
])

@section('title', 'Promo')

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" rel="stylesheet" type="text/css">
@endpush

@section('content')
    <div class="container-fluid ___promo-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Daftar Promo',
            ])
                @slot('addons')
                    <a class="btn btn-rounded btn-primary ripple mt-2 mt-sm-0" href="{{ route('admin.contents.promo.create') }}">Tambah Promo</a>
                @endslot

                <div class="row">
                    @foreach ($promos as $promo)
                        @include('elements.card-image', [
                            'id' => 'promo-' . $promo['id'],
                            'image' => $promo['image']['uri'],
                            'title' => $promo['name'],
                            'subtitle' => $promo['update'],
                            'edit' => route('admin.contents.promo.edit', ['promo' => $promo['id']]),
                            'delete' => 'onDeletePromo(' . $promo['id'] . ", '" . route('admin.contents.promo.destroy', ['promo' => $promo['id']]) . "');",
                        ])
                    @endforeach
                </div>
            @endcomponent
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>
@endpush

@push('scripts-app')
    <script src="{{ asset('js/admin/contents.promo.js') }}"></script>
    <script>
        @if(session('status'))
            $.toast({
                heading: 'Permintaan Berhasil',
                text: "{{ session('status') }}",
                hideAfter : 7000,
                position: 'top-right',
                icon: 'success',
                stack: false
            });
        @endif
    </script>
@endpush