routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Admin\AdminHomeController@index')->name('admin.home');

Route::resource('/settings', 'Admin\AdminSettingController', ['as' => 'admin'])->except(['index', 'show']);
Route::resource('/products', 'Admin\AdminProductController', ['as' => 'admin'])->except(['show']);

Route::resource('/contents/faq', 'Admin\AdminFaqController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/faq', 'Admin\AdminFaqController@updateOrdering')->name('admin.contents.faq.ordering');

Route::resource('/contents/term', 'Admin\AdminTermController', ['as' => 'admin.contents'])->only(['index']);

Route::resource('/contents/payment', 'Admin\AdminPaymentController', ['as' => 'admin.contents'])->except(['show']);
Route::put('/contents/payment', 'Admin\AdminPaymentController@updateOrdering')->name('admin.contents.payment.ordering');

Route::resource('/contents/partner', 'Admin\AdminPartnerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/testimony', 'Admin\AdminTestimonyController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/promo', 'Admin\AdminPromoController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/contents/banner', 'Admin\AdminBannerController', ['as' => 'admin.contents'])->except(['show']);
Route::resource('/metas', 'Admin\AdminMetaController', ['as' => 'admin'])->except(['show']);

Route::resource('/users', 'Admin\AdminUserController', ['as' => 'admin'])->except(['show']);
Route::get('/users/profile', 'Admin\AdminUserController@showProfile')->name('admin.users.profile');
Route::put('/users/profile/update', 'Admin\AdminUserController@updateProfile')->name('admin.users.profile.update');
Route::put('/users/photo/update', 'Admin\AdminUserController@updatePhoto')->name('admin.users.photo.update');
Route::get('/users/password', 'Admin\AdminUserController@showPassword')->name('admin.users.password');
Route::put('/users/password/update', 'Admin\AdminUserController@updatePassword')->name('admin.users.password.update');

Route::resource('/simulations/installment', 'Admin\AdminInstallmentController', ['as' => 'admin.simulations'])->except(['index', 'show']);
Route::resource('/simulations', 'Admin\AdminSimulationController', ['as' => 'admin'])->except(['show']);
Route::get('/simulations/branch/update', 'Admin\AdminSimulationController@updateBranches')->name('admin.simulations.branch.update');

app/Models/Banner.php
<?php

namespace App\Models;

use App\Models\Image;
use App\Models\Page;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Banner extends Model
{
    protected $guarded = [];

    public function image()
    {
        return $this->hasOne(Image::class, 'id', 'image_id')->withDefault(['path' => config('setting.default.placeholder')]);
    }

    public function page()
    {
        return $this->hasOne(Page::class, 'id', 'page_id')->withDefault(['name' => 'Tidak Diketahui']);
    }

    public function updater()
    {
        return $this->belongsTo(User::class, 'updated_by')->withDefault(['name' => 'Tidak Diketahui']);
    }

    public function setTitleAttribute($value)
    {
        if (is_null($value)) {
            $this->attributes['title'] = '';
        }
        else
        {
            $this->attributes['title'] = $value;
        }
    }

    public function setSubtitleAttribute($value)
    {
        if (is_null($value)) {
            $this->attributes['subtitle'] = '';
        }
        else
        {
            $this->attributes['subtitle'] = $value;
        }
    }

    public function getUpdateAttribute()
    {
        $name = $this->updater->name;
        $datetime = new Carbon($this->updated_at);
        return 'Pembaruan terakhir oleh ' . $name . ' pada ' . $datetime->setTimezone('Asia/Jakarta')->format('d-m-Y, H:i');
    }

    private function __populate($data, $image)
    {
        $dataWithoutBannerPage = array_except($data, ['image', 'page']);
        $dataWithPage = array_add($dataWithoutBannerPage, 'page_id', $data['page']);
        $dataWithImage = array_add($dataWithPage, 'image_id', $image->id);
        $dataWithUser = array_add($dataWithImage, 'updated_by', auth()->user()->id);

        return $dataWithUser;
    }

    public function add($data)
    {
        $image = Image::add($data['image']);

        return $this->create($this->__populate($data, $image));
    }

    public function edit($data)
    {
        $image = $this->image;
        if (array_has($data, 'image'))
        {
            Image::remove($this->image);
            $image = Image::add($data['image']);
        }

        return $this->update($this->__populate($data, $image));

    }

    public function remove()
    {
        Image::remove($this->image);
        return $this->delete();
    }
}

resources/views/admin/contents/banner/create.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'contents',
    ],
    'title' => 'Tambah Banner',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Konten',
            'href' => 'javascript:void(0);',
        ],
        [
            'title' => 'Banner',
            'href' => route('admin.contents.banner.index'),
        ],
        [
            'title' => 'Tambah Banner',
        ]
    ],
])

@section('title', 'Tambah Banner')

@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" type="text/css">
@endpush

@section('content')
    <div class="container-fluid ___product-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Tambah Banner',
                'addons' => null,
            ])
                <form class="row" method="POST" enctype="multipart/form-data" action="{{ route('admin.contents.banner.store') }}">
                    @csrf
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.uploader', [
                            'id' => 'image',
                            'name' => 'image',
                            'horizontal' => true,
                            'label' => 'GAMBAR BANNER',
                            'help' => 'Rekomendasi ukuran gambar 1920 x 1080 px',
                            'value' => old('image'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'title',
                            'name' => 'title',
                            'horizontal' => true,
                            'label' => 'JUDUL BANNER',
                            'placeholder' => 'Masukkan judul banner',
                            'value' => old('title'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'subtitle',
                            'name' => 'subtitle',
                            'horizontal' => true,
                            'label' => 'SUB-JUDUL BANNER',
                            'placeholder' => 'Masukkan sub-judul banner',
                            'value' => old('subtitle'),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.select', [
                            'id' => 'page',
                            'name' => 'page',
                            'horizontal' => true,
                            'label' => 'BERLAKU UNTUK HALAMAN',
                            'placeholder' => 'Pilih halaman',
                            'value' => old('page'),
                            'options' => $pages->map(function ($page) {
                                return [
                                    'value' => $page->id,
                                    'label' => $page->name,
                                ];
                            }),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8 mr-t-10 d-flex justify-content-end flex-column flex-sm-row">
                        <a href="{{ route('admin.contents.banner.index') }}"><button class="btn btn-rounded btn-outline-default ripple mr-sm-3 mb-2 mb-sm-0" type="button">Batalkan</button></a>
                        <button class="btn btn-rounded btn-primary ripple" type="submit">Tambah Banner</button>
                    </div>
                </form>
            @endcomponent
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
@endpush

resources/views/admin/contents/banner/edit.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'contents',
    ],
    'title' => 'Edit Banner',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Konten',
            'href' => 'javascript:void(0);',
        ],
        [
            'title' => 'Banner',
            'href' => route('admin.contents.banner.index'),
        ],
        [
            'title' => 'Edit Banner',
        ]
    ],
])

@section('title', 'Edit Banner')

@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" type="text/css">
@endpush

@section('content')
    <div class="container-fluid ___product-page">
        <div class="widget-list row">
            @component('elements.container', [
                'title' => 'Edit Banner',
                'addons' => null,
            ])
                <form class="row" method="POST" enctype="multipart/form-data" action="{{ route('admin.contents.banner.update', ['banner' => $banner['id']]) }}">
                    @csrf
                    @method('PUT')
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.uploader', [
                            'id' => 'image',
                            'name' => 'image',
                            'horizontal' => true,
                            'label' => 'GAMBAR BANNER',
                            'help' => 'Biarkan kosong jika tidak ingin mengubah. Rekomendasi ukuran gambar 1920 x 1080 px',
                            'value' => old('image', $banner['image']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'title',
                            'name' => 'title',
                            'horizontal' => true,
                            'label' => 'JUDUL BANNER',
                            'placeholder' => 'Masukkan judul banner',
                            'value' => old('title', $banner['title']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.text', [
                            'id' => 'subtitle',
                            'name' => 'subtitle',
                            'horizontal' => true,
                            'label' => 'SUB-JUDUL BANNER',
                            'placeholder' => 'Masukkan sub-judul banner',
                            'value' => old('subtitle', $banner['subtitle']),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8">
                        @include('elements.forms.select', [
                            'id' => 'page',
                            'name' => 'page',
                            'horizontal' => true,
                            'label' => 'BERLAKU UNTUK HALAMAN',
                            'placeholder' => 'Pilih halaman',
                            'value' => old('page', $banner['page']['id']),
                            'options' => $pages->map(function ($page) {
                                return [
                                    'value' => $page->id,
                                    'label' => $page->name,
                                ];
                            }),
                        ])
                    </div>
                    <div class="col-xs-12 col-md-10 col-lg-8 mr-t-10 d-flex justify-content-end flex-column flex-sm-row">
                        <a href="{{ route('admin.contents.banner.index') }}"><button class="btn btn-rounded btn-outline-default ripple mr-sm-3 mb-2 mb-sm-0" type="button">Batalkan</button></a>
                        <button class="btn btn-rounded btn-primary ripple" type="submit">Simpan Banner</button>
                    </div>
                </form>
            @endcomponent
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
@endpush

resources/views/admin/contents/banner/home.blade.php
@extends('layouts.main', [
    'sidebar' => [
        'name' => 'admin.sidebar',
        'active' => 'contents',
    ],
    'title' => 'Banner',
    'breadcrumbs' => [
        [
            'title' => 'Dashboard',
            'href' => route('admin.home'),
        ],
        [
            'title' => 'Konten',
            'href' => 'javascript:void(0);',
        ],
        [
            'title' => 'Banner',
        ]
    ],
])

@section('title', 'Banner')

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" rel="stylesheet" type="text/css">
@endpush

@push('styles-app')
    <link href="{{ asset('css/admin/contents.banner.css?v=1.0.5') }}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid ___product-page">
        <div class="widget-list row">
            @foreach ($pages as $page)
                @component('elements.container', [
                    'title' => 'Halaman ' . $page['name'],
                ])
                    @slot('addons')
                        <a class="btn btn-rounded btn-primary ripple mt-2 mt-sm-0" href="{{ route('admin.contents.banner.create') }}">Tambah Banner</a>
                    @endslot

                    <div class="___table">
                        <table class="table table-bordered ___table__banner">
                            <thead>
                                <tr>
                                    <th>Banner</th>
                                    <th>Judul</th>
                                    <th>Sub-Judul</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($banners as $banner)
                                    @if ($page['id'] == $banner['page_id'])
                                        <tr id="{{ 'banner-' . $banner['id'] }}">
                                            <td><img src="{{ $banner['image']['uri'] }}" alt="banner" /></td>
                                            <td>{{ $banner['title'] }}</td>
                                            <td>{{ $banner['subtitle'] }}</td>
                                            <td>
                                                <a class="text-primary" href="{{ route('admin.contents.banner.edit', ['banner' => $banner['id']]) }}"><i class="material-icons">edit</i></a>
                                                <a class="text-muted" onclick="{{ 'onDeleteBanner(' . $banner['id'] . ", '" . route('admin.contents.banner.destroy', ['banner' => $banner['id']]) . "');" }}"><i class="material-icons">delete</i></a>
                                            </td>
                                        </tr>
                                    @endif
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @endcomponent
            @endforeach
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.2/dist/sweetalert2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>
@endpush

@push('scripts-app')
    <script src="{{ asset('js/admin/contents.banner.js') }}"></script>
    <script>
        @if(session('status'))
            $.toast({
                heading: 'Permintaan Berhasil',
                text: "{{ session('status') }}",
                hideAfter : 7000,
                position: 'top-right',
                icon: 'success',
                stack: false
            });
        @endif
    </script>
@endpush